# Generated by Django 4.2.4 on 2023-08-29 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ai_chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=300, unique=True)),
                ('value', models.TextField(blank=True)),
            ],
        ),
    ]
