# Generated by Django 4.2.4 on 2023-08-29 04:26

from django.db import migrations


def forwards_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Model = apps.get_model('django_ai_chat', 'Model')
    model = Model(
        title='gpt-3.5-turbo',
        name='gpt-3.5-turbo',
        system_prompt='',
        temperature=1,
    )
    model.save(using=db_alias)

    AppVar = apps.get_model('django_ai_chat', 'AppVar')
    app_var = AppVar(key='django-ai-chat/model/default', value='gpt-3.5-turbo')
    app_var.save(using=db_alias)


def reverse_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Model = apps.get_model('django_ai_chat', 'Model')
    Model.objects.get(title='gpt-3.5-turbo').delete()
    AppVar = apps.get_model('django_ai_chat', 'AppVar')
    AppVar.objects.get(key='django-ai-chat/model/default').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('django_ai_chat', '0002_appvar'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
