# Generated by Django 4.2.4 on 2023-08-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_ai_chat', '0003_auto_20230829_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='role',
            field=models.CharField(default='user', max_length=100),
            preserve_default=False,
        ),
    ]
